### ISSUE TITLE
Please add a license to your repository

### ISSUE THREAD

**Issue by MooersLab** [JamesABaker/pymolrc_custom#1]
From your welcoming README.md file, you seem to be inviting people to use your pymolrc file.
However, your repository lacks a license file.
This means that you have given no one permission to use your software.
GitHub users will violate GitHub's terms if they use your software.
Please add a license file with the date of copyright. 
I suggest the permissive MIT license, which I use with most of my repositories.,
See here for more [information](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license).

**Comment by JamesABaker** [comment]
Hi @MooersLab, great spot! I'll add that now 😄
